// Shared category list — keep in sync with the job_category enum in the
// database (see supabase/migrations/0008_expand_job_categories.sql).
export const CATEGORIES: { value: string; label: string }[] = [
  { value: 'construction', label: 'Construction & Skilled Trades' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'it', label: 'Technology & IT' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'finance', label: 'Finance & Accounting' },
  { value: 'education', label: 'Education' },
  { value: 'retail', label: 'Retail' },
  { value: 'restaurant', label: 'Restaurants & Hospitality' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'transportation', label: 'Transportation & Logistics' },
  { value: 'warehouse', label: 'Warehouse' },
  { value: 'government', label: 'Government' },
  { value: 'sales', label: 'Sales' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'customer_service', label: 'Customer Service' },
  { value: 'hr', label: 'Human Resources' },
  { value: 'business', label: 'Business & Management' },
  { value: 'legal', label: 'Legal' },
  { value: 'science', label: 'Science & Research' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'arts_media', label: 'Arts & Media' },
  { value: 'security', label: 'Security' },
  { value: 'internships', label: 'Internships' },
  { value: 'freelance', label: 'Freelance & Gig Work' },
];
